
import "./globals.css";


export const metadata = {
  title: "home",
  description: "Generated by create next app",
};

// app/layout.jsx (if using the App Directory structure)
// OR
// pages/_app.js (if using the Pages Directory structure)

import { MatchProvider } from "./context/MatchContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MatchProvider>
          {children}
        </MatchProvider>
      </body>
    </html>
  );
}