// Import statements should be at the top
import "./globals.css";
import BottomNav from '../components/layout/bottomNav'; // Ensure the component name starts with an uppercase letter
import { MatchProvider } from "./context/MatchContext";

export const metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MatchProvider>
          <div className="min-h-screen flex flex-col">
            <main className="flex-grow">{children}</main>
            <BottomNav /> {/* Place BottomNav inside the body */}
          </div>
        </MatchProvider>
      </body>
    </html>
  );
}